services:
  # -----------------------------
  # 1. AI ENGINE (Backend)
  # -----------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nanosentri-backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/phi3_export/phi3_int4_final
      - PYTHONPATH=/app
    volumes:                 # <--- ADD THIS BLOCK
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    restart: unless-stopped

  # -----------------------------
  # 2. DASHBOARD (Frontend)
  # -----------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nanosentri-dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: unless-stopped